Sprint 2/step 2
dainiak/react-burger pull request #3
Opened 2023-07-17 19:29 UTC by dainiak

2023-07-17 19:48 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошо настроен и работает `Dnd`
- Созданы все необходимые типы экшенов
- Редьюсеры - чистые функции

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- При добавлении ингредиентов в конструктор - должен обновляться счетчик у каждого добавленного ингредиента. Для этого используйте компонент Counter из ui библиотекой.
- При нажатии кнопки "Оформить заказ" должен происходить запрос на бек. У вас уже есть postOrderByApi, но он не срабатывает.
- следует разделить экшены относящиеся к решению конкретной задачи по файлам
- разделите редьюсер на несколько 
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Более подробно смотрите описание проблемы в комментариях к pull-request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-17 19:48 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +    const ingredients = useSelector((store: any) => store.burgerConstructor.items);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-07-17 19:48 UTC, andryxxa93 commented on src/services/actions/index.tsx
> +import {MockData, MockOrder} from "../../utils/mock-data";
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2023-07-17 19:48 UTC, andryxxa93 commented on src/services/reducers/index.tsx
> +import { combineReducers } from 'redux';
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-07-17 19:48 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +                                        key={item._id + index.toString()}
**Можно лучше**
для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки `uuid` https://www.npmjs.com/package/uuid . А в key будет уже просто `key={ item.uuid }`

2023-07-18 07:26 UTC, andryxxa93 commented
**Необходимо исправить**

- Оформление заказа не работает. На это есть две причины:
1 - вы не переводите body запроса в строку. Это надо сделать через JSON.stringify. Так же необходимо в хедеры запроса добавить                 "Content-type": 'application/json'.
2 - У вас в body запроса уходят просто объекты булок, а не их айдишники.

<img width="1440" alt="Снимок экрана 2023-07-18 в 10 21 20" src="https://github.com/dainiak/react-burger/assets/60173362/ceab7458-cc3e-46df-9c39-d40c2c573c0a">

2023-07-18 08:00 UTC, dainiak commented on src/components/burger-constructor/burger-constructor.tsx
> +                                        key={item._id + index.toString()}
Fixed

2023-07-18 08:26 UTC, dainiak commented on src/components/burger-constructor/burger-constructor.tsx
> +    const ingredients = useSelector((store: any) => store.burgerConstructor.items);
Moved selectors into a different dir: services/selectors/

2023-07-18 17:14 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-19 08:38 UTC, merged