Sprint 3/step 1
dainiak/react-burger pull request #4
Opened 2023-08-05 07:52 UTC by dainiak

2023-08-05 08:16 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Правильно настроен роутинг модалок
- Ссылки в хедере меняют активность при изменении роутов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный юзер не должен иметь возможность сделать заказ
- Неправильно работает восстановление пароля. Новый пароль и код восстановления отсылаются не на тот ендпоинт. Пожалуйста обратите внимание на тех.задание.
- В инпут пароля на странице профиля невозможно что-либо ввести
- На странице профиля если что-то изменить в личных данных не появляются кнопки "Отмена" и "Сохранить".
- У ингредиентов в списке не отображаются названия.

<img width="489" alt="Снимок экрана 2023-08-05 в 11 11 21" src="https://github.com/dainiak/react-burger/assets/60173362/a24e5b91-0044-4f89-b16e-8ca3f8d60c14">

- После логаута можно попасть на страницу профиля 
<img width="1439" alt="Снимок экрана 2023-08-05 в 11 12 03" src="https://github.com/dainiak/react-burger/assets/60173362/8ec0f1c4-db52-49f3-ae22-71d19d6df09e">

- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.

- При ошибке запроса данных юзера ломается приложение. Вам необходимо добавить проверку успешности запроса. 

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

<img width="1440" alt="Снимок экрана 2023-08-05 в 11 14 52" src="https://github.com/dainiak/react-burger/assets/60173362/46bcc283-1239-456d-a4d7-5e4c9310172d">

**Можно лучше**
- наличие токена ещё не значит, что он будет принят сервером, поэтому правильно при прямом переходе на защищенную страницу даже при наличии токена следует отправлять запрос на сервер (например запрос получения данных пользователя) и только если запрос будет выполнен и токен принят, можно отображать защищенную страницу

На время выполнения этого запроса проверяющего актуальность токена нужно отображать прелоадер, а при завершении запроса в случае успеха отображать защищенный компонент, а в случае ошибки - очищать токен и перенаправлять на страницу входе
- После прохождения запроса на регистрацию лучше редиректить юзера на страницу логина

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-05 08:16 UTC, andryxxa93 commented on src/App.tsx
> +                    <Route path="/login" element={<LoginPage />}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-08-05 08:16 UTC, andryxxa93 commented on src/pages/login.tsx
> +    const onPasswordChange = (e: any) => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-08-05 09:51 UTC, dainiak commented on src/pages/login.tsx
> +    const onPasswordChange = (e: any) => {
Добавил, спасибо:)

2023-08-05 09:51 UTC, dainiak commented on src/App.tsx
> +                    <Route path="/login" element={<LoginPage />}/>
Сделал.

2023-08-05 10:06 UTC, dainiak commented
> Необходимо исправить:
> 
> * Не авторизованный юзер не должен иметь возможность сделать заказ
Поправил.


> * Неправильно работает восстановление пароля. Новый пароль и код восстановления отсылаются не на тот ендпоинт. 
Эндпоинт поменял.

> * В инпут пароля на странице профиля невозможно что-либо ввести


> * На странице профиля если что-то изменить в личных данных не появляются кнопки "Отмена" и "Сохранить".
> * У ингредиентов в списке не отображаются названия.
> 
> <img alt="Снимок экрана 2023-08-05 в 11 11 21" width="489" src="https://user-images.githubusercontent.com/60173362/258572076-a24e5b91-0044-4f89-b16e-8ca3f8d60c14.png">
> * После логаута можно попасть на страницу профиля
Действительно, возникает ошибка при логауте, но не понимаю пока, как её отдебажить…

> 
> <img alt="Снимок экрана 2023-08-05 в 11 12 03" width="1439" src="https://user-images.githubusercontent.com/60173362/258572175-8ec0f1c4-db52-49f3-ae22-71d19d6df09e.png">
> * Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
Поправил.


> **Можно лучше**
> 
> * наличие токена ещё не значит, что он будет принят сервером, поэтому правильно при прямом переходе на защищенную страницу даже при наличии токена следует отправлять запрос на сервер (например запрос получения данных пользователя) и только если запрос будет выполнен и токен принят, можно отображать защищенную страницу
> 
> На время выполнения этого запроса проверяющего актуальность токена нужно отображать прелоадер, а при завершении запроса в случае успеха отображать защищенный компонент, а в случае ошибки - очищать токен и перенаправлять на страницу входе

Добавил.

> 
> * После прохождения запроса на регистрацию лучше редиректить юзера на страницу логина
> 
Добави перенаправление в профиль.

2023-08-05 20:43 UTC, andryxxa93 commented
**Необходимо исправить**
- При логауте возникает ошибка. Всё дело в том, что вы `logoutUser` вызываете в двух местах сразу.

2023-08-05 21:13 UTC, dainiak commented
> **Необходимо исправить**
> 
> * При логауте возникает ошибка. Всё дело в том, что вы `logoutUser` вызываете в двух местах сразу.

Нашёл причину, кажется.

2023-08-06 09:56 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-06 11:36 UTC, merged